### ISSUE TITLE
AttributeError: 'Query' object has no attribute 'select_fields' with Django 1.6

### ISSUE THREAD

**Issue by olberger** [django-ldapdb/django-ldapdb#25]
Hi.

I've noticed a problem when upgrading from Django 1.5 to 1.6.

Now, I have this error : 
AttributeError: 'Query' object has no attribute 'select_fields' with Django 1.6

on a line like :
self.ldapuser = LdapUser.objects.get(uid=dpm.nickname)

where LdapUser inherits from ldapdb.models.Model
and has :
    uid  = CharField(db_column='uid', validators=[], primary_key=True)

Thanks in advance. Best regards
