### ISSUE TITLE
Django 1.6 :  'Query' object has no attribute 'select_fields'

### ISSUE THREAD

**Issue by hlepesant** [django-ldapdb/django-ldapdb#24]
I've justed tested with Django 1.6 and I got this kind of message.
Work well with 1.4.5

Regards,
Hug

``` python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 71, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/ldapdb/backends/ldap/compiler.py", line 131, in results_iter
    if self.query.select_fields:
AttributeError: 'Query' object has no attribute 'select_fields'
```
