### ISSUE TITLE
AttributeError: 'DatabaseWrapper' object has no attribute 'introspection'

### ISSUE THREAD

**Issue by zephir89** [django-ldapdb/django-ldapdb#106]
Hi!
After upgrading Django from 1.9 to 1.10.4 I get this error with 'makemigrations' command.
If I comment out 'ldap' connection in DATABASES setting, the issue is resolved.
Can you help me?
Thank you!

`
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/sielteid/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/venv/sielteid/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/sielteid/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/sielteid/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/sielteid/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 109, in handle
    loader.check_consistent_history(connection)
  File "/opt/venv/sielteid/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 276, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/opt/venv/sielteid/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/opt/venv/sielteid/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
AttributeError: 'DatabaseWrapper' object has no attribute 'introspection'
`

Daniele

**Comment by prusayn** [comment]
It's not working on any django 1.10 version.

**Comment by ikreb7** [comment]
django-ldapdb doesn't support Django 1.10. But you could try this:

Change the ``base.py`` like here.

    from django.db.backends.base.introspection import DatabaseIntrospection

    def __init__(self, *args, **kwargs):
        super(DatabaseWrapper, self).__init__(*args, **kwargs)

        # Charset used for LDAP text *values*
        self.charset = "utf-8"
        self.creation = DatabaseCreation(self)
        self.features = DatabaseFeatures(self)
        self.introspection = DatabaseIntrospections(self)
        self.ops = DatabaseOperations(self)
        self.validation = DatabaseValidation(self)
        self.settings_dict['SUPPORTS_TRANSACTIONS'] = True
  	self.autocommit = True

and then build it new. Report whether it solves the error, please. Also a pull request will be nice.

**Comment by jordanorc** [comment]
#109 - Pull request created. I think it's working now.

**Comment by zephir89** [comment]
Thank you!
